//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.15 at 10:37:07 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://wiktor.pl/first-soap-example", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.wiktor.first_soap_example;
